### ISSUE TITLE
Files watcher 

### ISSUE THREAD

**Issue by dimamarksman** [tettusud/merge-jsons-webpack-plugin#13] opened 2017-05-23 11:09 UTC
I'm wondering if it is possible to add a watcher to track  any changes in json and rewrite output file.

**Comment by dimamarksman** [comment] 2017-05-23 11:11
It would be useful for working with the webpack devserver

**Comment by tettusud** [comment] 2017-05-23 14:57
It should be already happening...get the latest and change a json ,it will compile and emit the output .
Please let me know if I didn't get your question right ?

**Comment by dimamarksman** [comment] 2017-05-23 16:49
It does not work for me. When i change a json which is not in the webpack entry but in the plugin group pattern it does not rewrite output json file

**Comment by tettusud** [comment] 2017-05-24 02:30
How are you starting your webpack dev server ?paste the start script here.
It should be working fine ,because previous issue I just fixed and users confirmed its working on their side.
 Use --inline flag while starting webpack dev server

**Comment by dimamarksman** [comment] 2017-05-24 06:54
Thank you for your reply!

I decided to test your repo :)

I cloned this repo and run project localy.

First of all when I try to `npm start` in the example folder i get an error:
```
merge-jsons-webpack-plugin\example\node_modules\webpack-dev-server\bin\webpack-dev-server.js:361
   Error: `output.path` needs to be an absolute path or `/`.
```
I fixed it by:
```
output: {
     path: path.resolve(__dirname, 'dist'),
     filename: "[name].bundle.js",
}
```
After it runs and compiles json succefully.

But when I change for instance `/jsons/file1.json` it does not update `./out/module1/module2/en.json`

Cheers

**Comment by tettusud** [comment] 2017-06-09 12:47
hi @dimamarksman ,are you still facing the issue? am closing the issue, if you need you can reopen it.

**Closed** 2017-06-09 13:24 UTC
