### ISSUE TITLE
Issue with webpack 4 beta0 and file emitting

### ISSUE THREAD

**Issue by pshurygin** [tettusud/merge-jsons-webpack-plugin#30] opened 2018-02-05 09:33 UTC
I'm having the following error while emmiting merged json files. Im' using webpack 4 beta0 + merge-jsons-webpack-plugin 1.0.13, guess this is a compatibility issue with new webpack version.

> 95% emitting unnamed compat plugin \node_modules\merge-jsons-webpack-plugin\index.js:67
>                         compilation.fileDependencies.push(f);
>                                                      ^
> 
> TypeError: compilation.fileDependencies.push is not a function
>     at fileDependencies.forEach (\node_modules\merge-jsons-webpack-plugin\index.js:67:54)
>     at Array.forEach (native)
>     at compiler.plugin (\node_modules\merge-jsons-webpack-plugin\index.js:64:39)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (\node_modules\tapable\lib\Hook.js:35:21)
>     at asyncLib.forEach.err (\node_modules\webpack\lib\Compiler.js:286:26)
>     at \node_modules\async\dist\async.js:473:16
>     at iteratorCallback (\node_modules\async\dist\async.js:1050:13)
>     at \node_modules\async\dist\async.js:958:16
>     at \node_modules\graceful-fs\graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:123:15)
> 
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "buildDev" "--scripts-prepend-node-path=auto"
> npm ERR! node v6.12.3
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE

And here is the config i use:

>         plugins: [
>             new MergeJsonWebpackPlugin({
>                 "output": {
>                     "groupBy": [
>                         {
>                             "pattern": "Frontend/translations/en/*.json",
>                             "fileName": "en.json"
>                         },
>                         {
>                             "pattern": "Frontend/translations/es/*.json",
>                             "fileName": "es.json"
>                         },
>                         {
>                             "pattern": "Frontend/translations/ru/*.json",
>                             "fileName": "ru.json"
>                         },
>                         {
>                             "pattern": "Frontend/translations/pt-BR/*.json",
>                             "fileName": "pt-BR.json"
>                         }
>                     ]
>                 }
>             })
>         ]

**Comment by tettusud** [comment] 2018-02-05 10:22
You are right in webpack4 it’s a Set I will handle it accordingly and update you

**Comment by tettusud** [comment] 2018-02-06 15:17
The issue is fixed now, please get the latest version 1.0.14 .

**Closed** 2018-02-07 01:37 UTC
